
{
  "qn1":{
    "caption":"第一份问卷",
    "time":"2016-6-15",
    "state":"未发布",
    "title":"性格分析调查表",
    "content":[
        {
          "question":"性别",
          "type":"radio",
          "optionss":["男","女"]
        },
        {
          "question":"爱吃的水果",
          "type":"radio",
          "optionss":["苹果","梨"]
        },
        {
          "question":"单选题",
          "type":"radio",
          "optionss":["选项一","选项二"]
        },
         {
          "question":"多选题",
          "type":"checkbox",
          "optionss":["选项一","选项二","选项三","选项四"]
        },
         {
          "question":"多选题",
          "type":"checkbox",
          "optionss":["选项一","选项二","选项三","选项四"]
        },
         {
          "question":"多选题",
          "type":"checkbox",
          "options":["选项一","选项二","选项三","选项四"]
        },
        {
          "question":"文本题",
          "type":"textarea",
          "flag":"false"
        }          
    ]
  },
  "qn2":{
    "caption":"第二份问卷",
    "time":"2016-5-12",
    "state":"发布结束",
    "title":"这里是标题",
    "content":[
        {
          "question":"单选题",
          "type":"radio",
          "options":["选项一","选项二"]
        },
        {
          "question":"单选题",
          "type":"radio",
          "options":["选项一","选项二"]
        },
        {
          "question":"单选题",
          "type":"radio",
          "options":["选项一","选项二"]
        },
         {
          "question":"多选题",
          "type":"checkbox",
          "options":["选项一","选项二","选项三","选项四"]
        },
         {
          "question":"多选题",
          "type":"checkbox",
          "options":["选项一","选项二","选项三","选项四"]
        },
         {
          "question":"多选题",
          "type":"checkbox",
          "options":["选项一","选项二","选项三","选项四"]
        },
        {
          "question":"文本题",
          "type":"textarea",
          "flag":"false"
        }          
    ]
  },
  "qn3":{
    "caption":"第三份问卷",
    "time":"2016-6-13",
    "state":"发布中",
    "title":"这里是标题",
    "content":[
        {
          "question":"单选题",
          "type":"radio",
          "options":["选项一","选项二"]
        },
        {
          "question":"单选题",
          "type":"radio",
          "options":["选项一","选项二"]
        },
        {
          "question":"单选题",
          "type":"radio",
          "options":["选项一","选项二"]
        },
         {
          "question":"多选题",
          "type":"checkbox",
          "options":["选项一","选项二","选项三","选项四"]
        },
         {
          "question":"多选题",
          "type":"checkbox",
          "options":["选项一","选项二","选项三","选项四"]
        },
         {
          "question":"多选题",
          "type":"checkbox",
          "options":["选项一","选项二","选项三","选项四"]
        },
        {
          "question":"文本题",
          "type":"textarea",
          "flag":"false"
        }          
    ]
  }
}